name: Frontend Pipe
run-name: QA-Pipeline for Frontend

on:
  pull_request:
    paths:
      - web-app/**
      - .github/workflows/app.yml

env:
  APP_DIR: ./web-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Save Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

  component_tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Check code style
        run: npx prettier . --check
        working-directory: ${{ env.APP_DIR }}

      - name: Check lint
        run: npm run lint
        working-directory: ${{ env.APP_DIR }}

  #    - name: Run components tests
  #      run: CI=true npm test -- --coverage --watchAll=false
  #      working-directory: ${{ env.APP_DIR }}
  #      env:
  #        CI: true

      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
      #  with:
      #    projectBaseDir: ${{ env.APP_DIR }}
