name: App Pipe
run-name: Pipeline for the App

on:
  push:
    paths:
      - app/**
      - .github/workflows/app.yml
env:
  APP_DIR: ./app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Save Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

  compontent_tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@main
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Run components tests
        run: CI=true npm test -- --coverage --watchAll=false
        working-directory: ${{ env.APP_DIR }}
        env:
          CI: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
        with:
          projectBaseDir: ${{ env.APP_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: compontent_tests
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}
      - name: Build App
        run: npm run build
        working-directory: ${{ env.APP_DIR }}
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: ./app/build/
          server-dir: html/app/
          server: 31.220.126.208
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
