name: Deploy App
run-name: Deployment for the App

on:
  push:
    paths:
      - test/**
      - .github/workflows/app_deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          local-dir: ./test
          ftp-server: sftp://${{ secrets.REMOTE_USER }}.mittwaldserver.info/html/
          ftp-username: ${{ secrets.REMOTE_USER }}
          ftp-password: ${{ secrets.REMOTE_PASSWORD }}
