name: Deploy App
run-name: Deployment for the App

on:
  push:
    paths:
      - test/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          local-dir: ./test
          protocol: ftps
          ftp-server: ftp://p666144.mittwaldserver.info/html/
          ftp-username: ${{ secrets.REMOTE_USER }}
          ftp-password: ${{ secrets.REMOTE_PASSWORD }}
