name: App QA
run-name: QA for the App

on:
  push:
    paths:
      - app/**

env:
  APP_DIR: ./app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@v2
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Save Package cache
        uses: actions/cache@v2
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

  compontent_tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Package cache
        uses: actions/cache@v2
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Run components tests
        run: CI=true npm test -- --coverage --watchAll=false
        working-directory: ${{ env.APP_DIR }}
        env:
          CI: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
        with:
          projectBaseDir: ${{ env.APP_DIR }}
