name: Deploy to GitHub Pages

on:
  push:
    paths:
      - doku/**
    branches:
      - main

env:
  DOKU_DIR: ./doku

jobs:
  deploy:
    name: Deploy to GitHub Pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore Package cache
        uses: actions/cache@v2
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Save Package cache
        uses: actions/cache@v2
        with:
          path: ~/.package/cache
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}

      - name: Build website
        run: npm build
        working-directory: ${{ env.APP_DIR }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doku/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
