name: QA
run-name: QA Action for the APP, Server and e2e
on: [push]

    
env:
  APP_DIR: ./app
  SERVER_DIR: ./server

jobs:
  app_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.APP_DIR }}
        
      - name: Run components tests
        run: npm test --coverage
        working-directory: ${{ env.APP_DIR }}
    
  server_tests:
    runs-on: ubuntu-latest
    
    steps:
        - uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
    
        - name: Check repository
          uses: actions/checkout@v2

        - name: Install dependencies
          run: composer install
          working-directory: ${{ env.SERVER_DIR }}
          
        - name: Run code style tests
          run: vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run
          working-directory: ${{ env.SERVER_DIR }}
          
        - name: Run unit tests
          run: vendor/bin/phpunit --configuration ./phpunit.xml
          working-directory: ${{ env.SERVER_DIR }}
          
        - name: Run archithekture tests
          run: vendor/bin/deptrac analyse --report-uncovered
          working-directory: ${{ env.SERVER_DIR }}
