name: Server QA
run-name: QA for the Server

on:
  push:
    paths:
      - server/**

env:
  SERVER_DIR: ./server

jobs:
  server_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install
        working-directory: ${{ env.SERVER_DIR }}

      - name: Run code style tests
        run: vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run
        working-directory: ${{ env.SERVER_DIR }}

      - name: Run unit tests
        run: vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Unit
        working-directory: ${{ env.SERVER_DIR }}

      - name: Run feature tests
        run: vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Feature
        working-directory: ${{ env.SERVER_DIR }}

      - name: Run architecture tests
        run: vendor/bin/deptrac analyse --report-uncovered
        working-directory: ${{ env.SERVER_DIR }}
