name: Server QA
run-name: QA for the Server

on:
  push:
    paths:
      - server/**

env:
  SERVER_DIR: ./server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: graphviz

      - name: Check repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ${{ env.SERVER_DIR }}

  feature_tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Run feature tests
        run: vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Feature --testdox
        working-directory: ${{ env.SERVER_DIR }}

  unit_tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Unit --testdox
        working-directory: ${{ env.SERVER_DIR }}

  code_style_test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Run code style tests
        run: vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run
        working-directory: ${{ env.SERVER_DIR }}

  architecture_test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Run architecture tests
        run: vendor/bin/deptrac analyse --report-uncovered
        working-directory: ${{ env.SERVER_DIR }}

      - name: check whats happen
        run: ls -la
