name: Semantic Versioning
run-name: Version Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Debug Semantic Release Output
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          echo "New release version: ${{ steps.semantic-release.outputs.new_release_version }}"
          echo "Release notes: ${{ steps.semantic-release.outputs.new_release_notes }}"

    outputs:
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
